### ISSUE TITLE
`pro-gallery-renderer` component includes wrong class names

### ISSUE THREAD

**Issue by mastertheblaster** [wix-incubator/rich-content#18]
IMHO there should be no `_-node_modules-...`
```scss
_-node_modules-pro-gallery-renderer-dist-src-components-styles-global__pro-circle-preloader__2qPIF {
  -webkit-animation: _-node_modules-pro-gallery-renderer-dist-src-components-styles-global__semi-rotate__1B3Bd 1s linear infinite;
          animation: _-node_modules-pro-gallery-renderer-dist-src-components-styles-global__semi-rotate__1B3Bd 1s linear infinite;
  height: 30px;
  left: 50%;
  margin-left: -15px;
  margin-top: -15px;
  overflow: hidden;
  position: relative;
  -webkit-transform-origin: 100% 50%;
          transform-origin: 100% 50%;
  width: 15px; }
```
